services:
  frontend:
    image: dadarou/frontend
    build: frontend
    volumes:
      # VOLUME:CONTAINER_PATH
      ## PROD ##
      - ~/website-volume/database:/app/database
      ## DEV ##
      # - /home/daniel/dadabot site/website-final/frontend/database:/app/database
    restart: always

  backend:
    image: dadarou/backend
    build: backend
    restart: always

  proxy:
    image: dadarou/proxy
    build: proxy
    ports:
      - 8080:80
    restart: always
